
GlobalApiKey = "exampleexampleexampleexample"
Email = "example@example.com"
Domain = "example.com"
TargetDomainList = ["hoge.example.com", "moge.example.com"]
UseLineNotify = false
LineNotifyToken = "exampleexampleexampleexample"
